
import React from 'react';
import { MappingSet } from '../types';
import { PerspectiveIcon, CreateIcon, EditNoteIcon, CheckCircleIcon, CompareArrowsIcon, GeminiIcon, MaterialIcon, WandSparklesIcon } from './Icons';

interface MappingSelectorProps {
  mappingSets: MappingSet[];
  selectedIndices: number[];
  onSelect: (index: number) => void;
  isLoading: boolean;
  onStartCustom: () => void;
  isCustomMode: boolean;
  exploredIndices: Set<number>;
  onCompare: () => void;
  isComparisonMode: boolean;
  onToggleComparisonMode: () => void;
}

const MappingSelector: React.FC<MappingSelectorProps> = ({ mappingSets, selectedIndices, onSelect, isLoading, onStartCustom, isCustomMode, exploredIndices, onCompare, isComparisonMode, onToggleComparisonMode }) => {
  return (
    <div className="my-6">
      <div className="flex flex-wrap items-center justify-between gap-4 mb-4">
        <h3 className="text-lg font-semibold text-slate-600 flex items-center justify-start gap-2">
          <PerspectiveIcon />
          <span>Explore Mappings to Create Different Perspectives</span>
        </h3>
        <div className="flex items-center gap-3">
          <button 
            onClick={onToggleComparisonMode} 
            disabled={isLoading}
            className={`flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:bg-slate-400
              ${isComparisonMode 
                ? 'text-white bg-slate-700 hover:bg-slate-800 focus:ring-slate-500' 
                : 'text-white bg-blue-600 hover:bg-blue-700 focus:ring-blue-500'
              }`}
          >
            <CompareArrowsIcon />
            <span>{isComparisonMode ? 'Cancel' : 'Compare Perspectives'}</span>
          </button>
          
          {isComparisonMode && selectedIndices.length >= 2 && (
            <button 
              onClick={onCompare} 
              disabled={isLoading}
              className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-green-600 rounded-lg hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 disabled:bg-slate-400"
            >
              <WandSparklesIcon />
              <span>Compare ({selectedIndices.length})</span>
            </button>
          )}
        </div>
      </div>

       {isComparisonMode && (
          <div className="p-3 mb-4 bg-blue-50 border border-blue-200 rounded-lg text-sm text-blue-700" role="alert">
              <strong>Comparison Mode:</strong> Select up to 3 perspectives to analyze them side-by-side.
          </div>
      )}

      <div className="flex flex-wrap justify-start gap-3 items-stretch">
        {mappingSets.map((set, index) => {
           const isSelected = selectedIndices.includes(index) && !isCustomMode;
           const isCustom = set.custom;
           const isExplored = exploredIndices.has(index);
           const isDisabled = isComparisonMode && selectedIndices.length >= 3 && !isSelected;
           
           const baseClasses = 'relative px-4 py-2 text-sm font-medium rounded-lg transition-all duration-200 border-2 flex flex-col items-start text-left';
           let styleClasses = '';
           if (isSelected) {
               styleClasses = isCustom 
                   ? 'bg-indigo-600 text-white border-indigo-600 shadow-lg'
                   : 'bg-blue-600 text-white border-blue-600 shadow-lg';
           } else {
               styleClasses = isCustom
                   ? 'bg-white text-slate-700 border-indigo-300 hover:bg-indigo-50 hover:border-indigo-400'
                   : 'bg-white text-slate-700 border-slate-300 hover:bg-slate-100 hover:border-slate-400';
           }
           const disabledClasses = 'disabled:opacity-50 disabled:cursor-not-allowed';

           return (
            <button
                key={index}
                onClick={() => onSelect(index)}
                disabled={isLoading || isDisabled}
                className={`${baseClasses} ${styleClasses} ${disabledClasses}`}
            >
                <div className="font-bold flex items-center gap-1">
                    {set.icon ? <MaterialIcon iconName={set.icon} className="text-base" /> : (isCustom ? <EditNoteIcon className="text-base" /> : <GeminiIcon className="text-base" />)}
                    <span>{set.name}</span>
                    {isExplored && <CheckCircleIcon className={`text-base ml-1 ${isSelected ? 'text-white' : 'text-green-500'}`} />}
                </div>
                <div className="text-xs">{set.description}</div>
                {!isCustom && <GeminiIcon className="absolute top-1 right-1 text-xs text-blue-400" title="Generated by AI"/>}
            </button>
           )
        })}
        <button
            onClick={onStartCustom}
            disabled={isLoading}
            className={`px-4 py-2 text-sm font-medium rounded-lg transition-all duration-200 border-2 flex items-center gap-2
            ${
              isCustomMode
                ? 'bg-indigo-600 text-white border-indigo-600 shadow-lg'
                : 'bg-white text-slate-700 border-slate-300 hover:bg-slate-100 hover:border-slate-400'
            } disabled:opacity-50 disabled:cursor-not-allowed`}
          >
              <CreateIcon />
              <span className="font-bold">Create Your Own</span>
          </button>
      </div>
    </div>
  );
};

export default MappingSelector;
